import React from "react";
import { FaRegHospital } from "react-icons/fa";
import { HiOutlineAcademicCap, HiOutlineChartSquareBar } from "react-icons/hi";
import { RiCustomerService2Line, RiDashboardLine } from "react-icons/ri";
import { BiErrorAlt } from "react-icons/bi";
import { BsCart4, BsCurrencyBitcoin } from "react-icons/bs";
import { MdOutlineAnalytics, MdOutlineManageAccounts } from "react-icons/md";
import { ImFeed, ImLab } from "react-icons/im";
import { GrDatabase, GrNavigate } from "react-icons/gr";
import { VscTable, VscTools } from "react-icons/vsc";
import { AiOutlineLayout, AiOutlineUnorderedList } from "react-icons/ai";
import { RoutePermittedRole } from "@crema/constants/AppEnums";

const routesConfig = [
  {
    id: "app",
    title: "Application",
    messageId: "sidebar.application",
    type: "group",
    children: [
      {
        id: "healthCare",
        title: "Health Care",
        messageId: "sidebar.healthCare",
        type: "item",
        permittedRole: [RoutePermittedRole.User],
        icon: <FaRegHospital />,
        url: "/dashboards/health-care",
      },
      {
        id: "e-commerce",
        title: "E-Commerce",
        messageId: "sidebar.app.dashboard.eCommerce",
        type: "item",
        permittedRole: [RoutePermittedRole.User],
        icon: <BsCart4 />,
        url: "/dashboards/e-commerce",
      },
    ],
  },
  {
    id: "mui",
    title: "MUI Components",
    messageId: "sidebar.mui",
    type: "group",
    children: [
      {
        id: "inputs",
        title: "Inputs",
        messageId: "sidebar.mui.inputs",
        type: "collapse",
        icon: "input",
        children: [
          {
            id: "buttons",
            title: "Buttons",
            messageId: "sidebar.mui.inputs.buttons",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/buttons",
          },
          {
            id: "button-group",
            title: "Button Group",
            messageId: "sidebar.mui.inputs.buttonGroup",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/button-group",
          },
          {
            id: "checkboxes",
            title: "Checkboxes",
            messageId: "sidebar.mui.inputs.checkboxes",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/checkboxes",
          },
          {
            id: "fab",
            title: "Fab",
            messageId: "sidebar.mui.inputs.fab",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/floating-action-button",
          },
          {
            id: "radios",
            title: "Radio Button",
            messageId: "sidebar.mui.inputs.radio",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/radios",
          },
          {
            id: "rating",
            title: "Rating",
            messageId: "sidebar.mui.util.rating",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/rating",
          },
          {
            id: "selects",
            title: "Selects",
            messageId: "sidebar.mui.inputs.selects",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/selects",
          },
          {
            id: "slider",
            title: "Slider",
            messageId: "sidebar.mui.inputs.slider",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/slider",
          },
          {
            id: "switches",
            title: "Switches",
            messageId: "sidebar.mui.inputs.switches",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/switches",
          },
          {
            id: "textField",
            title: "Text Field",
            messageId: "sidebar.mui.inputs.textField",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/text-fields",
          },
          {
            id: "transfer",
            title: "Transfer List",
            messageId: "sidebar.mui.inputs.transfer",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/transfer-list",
          },
          {
            id: "toggle-buttons",
            title: "Toggle Buttons",
            messageId: "sidebar.mui.util.toggleButtons",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/inputs/toggle-buttons",
          },
        ],
      },
      {
        id: "dataDisplay",
        title: "Data Display",
        messageId: "sidebar.mui.dataDisplay",
        type: "collapse",
        icon: <GrDatabase />,
        children: [
          {
            id: "avatars",
            title: "Avatars",
            messageId: "sidebar.mui.dataDisplay.avatars",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/avatars",
          },
          {
            id: "badges",
            title: "Badges",
            messageId: "sidebar.mui.dataDisplay.badges",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/badges",
          },
          {
            id: "chips",
            title: "Chips",
            messageId: "sidebar.mui.dataDisplay.chips",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/chips",
          },
          {
            id: "divider",
            title: "Divider",
            messageId: "sidebar.mui.dataDisplay.divider",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/divider",
          },
          {
            id: "lists",
            title: "Lists",
            messageId: "sidebar.mui.dataDisplay.lists",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/lists",
          },
          {
            id: "tables",
            title: "Tables",
            messageId: "sidebar.mui.dataDisplay.tables",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/tables",
          },
          {
            id: "tooltip",
            title: "Tooltip",
            messageId: "sidebar.mui.dataDisplay.tooltip",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/tooltip",
          },
          {
            id: "typography",
            title: "Typography",
            messageId: "sidebar.mui.dataDisplay.typography",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/data-display/typography",
          },
        ],
      },
      {
        id: "navigation",
        title: "Navigation",
        messageId: "sidebar.mui.navigation",
        type: "collapse",
        icon: <GrNavigate />,
        children: [
          {
            id: "bottomNavigation",
            title: "Bottom Navigation",
            messageId: "sidebar.mui.navigation.bottom",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/bottom-navigation",
          },
          {
            id: "breadcrumbs",
            title: "Breadcrumbs",
            messageId: "sidebar.mui.navigation.breadcrumbs",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/breadcrumbs",
          },
          {
            id: "drawers",
            title: "Drawers",
            messageId: "sidebar.mui.navigation.drawers",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/drawers",
          },
          {
            id: "links",
            title: "Links",
            messageId: "sidebar.mui.navigation.links",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/links",
          },
          {
            id: "menus",
            title: "Menus",
            messageId: "sidebar.mui.navigation.menus",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/menus",
          },
          {
            id: "pagination",
            title: "Pagination",
            messageId: "sidebar.mui.navigation.pagination",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/pagination",
          },
          {
            id: "speed-dial",
            title: "Speed Dial",
            messageId: "sidebar.mui.navigation.speedDial",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/speed-dial",
          },
          {
            id: "steppers",
            title: "Steppers",
            messageId: "sidebar.mui.navigation.steppers",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/steppers",
          },
          {
            id: "tabs",
            title: "Tabs",
            messageId: "sidebar.mui.navigation.tabs",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/navigation/tabs",
          },
        ],
      },
      {
        id: "surface",
        title: "Surface",
        messageId: "sidebar.mui.surface",
        type: "collapse",
        icon: "surround_sound",
        children: [
          {
            id: "appBar",
            title: "App Bar",
            messageId: "sidebar.mui.surface.appBar",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/surface/appbar",
          },
          {
            id: "accordion",
            title: "Accordion",
            messageId: "sidebar.mui.surface.accordion",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/surface/accordion",
          },
          {
            id: "cards",
            title: "Cards",
            messageId: "sidebar.mui.surface.cards",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/surface/cards",
          },
          {
            id: "paper",
            title: "Paper",
            messageId: "sidebar.mui.surface.paper",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/surface/paper",
          },
        ],
      },
      {
        id: "feedback",
        title: "feedback",
        messageId: "sidebar.mui.feedback",
        type: "collapse",
        icon: <ImFeed />,
        children: [
          {
            id: "alert",
            title: "Alert",
            messageId: "sidebar.mui.feedback.alert",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/feedback/alert",
          },
          {
            id: "backdrop",
            title: "Backdrop",
            messageId: "sidebar.mui.feedback.backdrop",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/feedback/backdrop",
          },
          {
            id: "dialog",
            title: "Dialog",
            messageId: "sidebar.mui.feedback.dialog",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/feedback/dialog",
          },
          {
            id: "progress",
            title: "Progress",
            messageId: "sidebar.mui.feedback.progress",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/feedback/progress",
          },
          {
            id: "skeleton",
            title: "Skeleton",
            messageId: "sidebar.mui.feedback.skeleton",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/feedback/skeleton",
          },
          {
            id: "snackbars",
            title: "Snackbars",
            messageId: "sidebar.mui.feedback.snackbars",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/mui/feedback/snackbars",
          },
        ],
      },
    ],
  },
  {
    id: "extra-pages",
    title: "Extra Pages",
    messageId: "sidebar.pages.extraPages",
    type: "group",
    children: [
      {
        id: "account",
        title: "Account",
        messageId: "sidebar.pages.extraPages.account",
        type: "item",
        permittedRole: [RoutePermittedRole.User, RoutePermittedRole.Admin],
        icon: <MdOutlineManageAccounts />,
        url: "/my-profile",
      },
      {
        id: "list-type",
        title: "User List",
        messageId: "sidebar.pages.userList",
        type: "collapse",
        icon: <AiOutlineUnorderedList />,
        children: [
          {
            id: "morden",
            title: "Modern",
            messageId: "sidebar.pages.userList.modern",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/list-type/morden",
          },
          {
            id: "standard",
            title: "Standard",
            messageId: "sidebar.pages.userList.standard",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/list-type/standard",
          },
          {
            id: "flat",
            title: "Flat",
            messageId: "sidebar.pages.userList.flat",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/list-type/flat",
          },
        ],
      },
      {
        id: "error-pages",
        title: "Error Pages",
        messageId: "sidebar.pages.errorPages",
        type: "collapse",
        icon: <BiErrorAlt />,
        children: [
          {
            id: "error-401",
            title: "402",
            messageId: "sidebar.pages.errorPages.401",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/error-401",
          },
          {
            id: "error-403",
            title: "403",
            messageId: "sidebar.pages.errorPages.403",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/error-403",
          },
          {
            id: "error-404",
            title: "404",
            messageId: "sidebar.pages.errorPages.404",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/error-404",
          },
          {
            id: "error-500",
            title: "500",
            messageId: "sidebar.pages.errorPages.500",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/error-500",
          },
          {
            id: "error-503",
            title: "503",
            messageId: "sidebar.pages.errorPages.503",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/error-503",
          },
          {
            id: "maintenance",
            title: "Maintenance",
            messageId: "sidebar.pages.errorPages.maintenance",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/maintenance",
          },
          {
            id: "coming-soon",
            title: "Coming Soon",
            messageId: "sidebar.pages.errorPages.comingSoon",
            type: "item",
            permittedRole: [RoutePermittedRole.User],
            url: "/error-pages/coming-soon",
          },
        ],
      },
    ],
  },
];
export default routesConfig;
